version: "3.9"
services:
  app:
    build:
      args:
        user: queue_fibonacci
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: queue_fibonacci
    container_name: queue_fibonacci_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - queue_fibonacci

  nginx:
    image: nginx:alpine
    container_name: queue_fibonacci_nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - queue_fibonacci

  db:
    image: mysql:8.0.30
    container_name: queue_fibonacci_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_queue_fibonacci
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: pass_queue_fibonacci
      MYSQL_USER: user_queue_fibonacci
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - queue_fibonacci

networks:
    queue_fibonacci:
        driver: bridge
